server:
  port: 8080

spring:
  application:
    name: gefrierschrank-backend
  
  datasource:
    url: jdbc:h2:file:./data/gefrierschrank_db;AUTO_RECONNECT=TRUE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    
  h2:
    console:
      enabled: true
      path: /h2-console
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin123}

jwt:
  secret: ${JWT_SECRET:mySecretKey12345678901234567890123456789012345678901234567890}
  expiration: 86400000 # 24 hours

cors:
  allowed-origins: "http://localhost:3000,http://localhost:5173"

logging:
  level:
    com.gefrierschrank: DEBUG
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always